"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env
load_dotenv(BASE_DIR / ".env", override=True)


# ============================================================
# Security
# ============================================================

SECRET_KEY = os.getenv("SECRET_KEY")

# Production safety: DEBUG defaults to False if omitted or empty.
# For local development, set DEBUG=True in your local .env file.
DEBUG = os.getenv("DEBUG", "False").lower() in ("true", "1", "t", "yes")

# Allowed hosts parsed from environment (comma-separated).
# Defaults to localhost and loopback for local development.
_raw_hosts = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost,[::1],testserver")
ALLOWED_HOSTS = [host.strip() for host in _raw_hosts.split(",") if host.strip()]
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["127.0.0.1", "localhost", "[::1]"]
if "testserver" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append("testserver")

# Railway dynamic public domain support
_railway_domain = os.getenv("RAILWAY_PUBLIC_DOMAIN", "").strip()
if _railway_domain and _railway_domain not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_railway_domain)
if os.getenv("RAILWAY_ENVIRONMENT") and ".railway.app" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(".railway.app")


def parse_security_settings(env=None, debug=None):
    """
    Parses reverse-proxy and cookie security settings from environment variables.
    """
    if env is None:
        env = os.environ
    if debug is None:
        debug = env.get("DEBUG", "False").lower() in ("true", "1", "t", "yes")

    use_proxy_ssl = env.get("USE_SECURE_PROXY_SSL_HEADER", "False").lower() in (
        "true",
        "1",
        "t",
        "yes",
    )
    proxy_ssl_header = ("HTTP_X_FORWARDED_PROTO", "https") if use_proxy_ssl else None

    session_cookie_secure = env.get(
        "SESSION_COOKIE_SECURE", "False" if debug else "True"
    ).lower() in ("true", "1", "t", "yes")

    csrf_cookie_secure = env.get(
        "CSRF_COOKIE_SECURE", "False" if debug else "True"
    ).lower() in ("true", "1", "t", "yes")

    ssl_redirect = env.get("SECURE_SSL_REDIRECT", "False").lower() in (
        "true",
        "1",
        "t",
        "yes",
    )

    raw_hsts = (env.get("SECURE_HSTS_SECONDS") or "0").strip()
    try:
        hsts_seconds = int(raw_hsts) if raw_hsts else 0
    except ValueError:
        hsts_seconds = 0

    return {
        "SECURE_PROXY_SSL_HEADER": proxy_ssl_header,
        "SESSION_COOKIE_SECURE": session_cookie_secure,
        "CSRF_COOKIE_SECURE": csrf_cookie_secure,
        "SECURE_SSL_REDIRECT": ssl_redirect,
        "SECURE_HSTS_SECONDS": hsts_seconds,
    }


_security_cfg = parse_security_settings(debug=DEBUG)
SECURE_PROXY_SSL_HEADER = _security_cfg["SECURE_PROXY_SSL_HEADER"]
SESSION_COOKIE_SECURE = _security_cfg["SESSION_COOKIE_SECURE"]
CSRF_COOKIE_SECURE = _security_cfg["CSRF_COOKIE_SECURE"]
SECURE_SSL_REDIRECT = _security_cfg["SECURE_SSL_REDIRECT"]
SECURE_HSTS_SECONDS = _security_cfg["SECURE_HSTS_SECONDS"]





# ============================================================
# Application definition
# ============================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "rest_framework",
    "drf_spectacular",
    "corsheaders",
    # Local apps
    "hiring",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "config.urls"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "hiring" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "config.wsgi.application"


# ============================================================
# Database Configuration (MySQL 8.0+ / Amazon RDS)
# ============================================================

from django.core.exceptions import ImproperlyConfigured

VALID_DB_SSL_MODES = ("DISABLED", "PREFERRED", "REQUIRED", "VERIFY_CA", "VERIFY_IDENTITY")


def _parse_int_setting(val, default: int, min_val: int = 0) -> int:
    """Safely parse integer settings with default fallback and minimum bound."""
    if val is None:
        return default
    try:
        parsed = int(str(val).strip())
        return parsed if parsed >= min_val else default
    except (ValueError, TypeError):
        return default


def build_database_config(env=None) -> dict:
    """
    Builds the Django DATABASES['default'] configuration dictionary
    supporting local development, secure Amazon RDS, and Railway MySQL services.
    """
    get_env = env.get if env is not None else os.getenv

    # Parse connection string if provided (e.g. Railway MYSQL_URL or DATABASE_URL)
    url_name = url_user = url_pass = url_host = url_port = None
    raw_db_url = get_env("DATABASE_URL") or get_env("MYSQL_URL")
    if raw_db_url and str(raw_db_url).strip().startswith("mysql://"):
        try:
            from urllib.parse import urlparse
            parsed = urlparse(str(raw_db_url).strip())
            url_name = parsed.path.lstrip("/") if parsed.path else None
            url_user = parsed.username
            url_pass = parsed.password
            url_host = parsed.hostname
            url_port = parsed.port
        except Exception:
            pass

    db_connect_timeout = _parse_int_setting(get_env("DB_CONNECT_TIMEOUT"), default=10, min_val=1)
    db_conn_max_age = _parse_int_setting(get_env("DB_CONN_MAX_AGE"), default=60, min_val=0)
    db_conn_health_checks_raw = get_env("DB_CONN_HEALTH_CHECKS")
    db_conn_health_checks = (
        str(db_conn_health_checks_raw).strip().lower() in ("true", "1", "yes")
        if db_conn_health_checks_raw is not None
        else (db_conn_max_age > 0)
    )

    port_val = get_env("DB_PORT") or get_env("MYSQLPORT") or (str(url_port) if url_port else None)
    db_port = _parse_int_setting(port_val, default=3306, min_val=1)

    db_name = get_env("DB_NAME") or get_env("MYSQLDATABASE") or url_name
    db_user = get_env("DB_USER") or get_env("MYSQLUSER") or url_user
    db_password = get_env("DB_PASSWORD") or get_env("MYSQLPASSWORD") or url_pass
    db_host = get_env("DB_HOST") or get_env("MYSQLHOST") or url_host or "127.0.0.1"

    db_options = {
        "charset": "utf8mb4",
        "connect_timeout": db_connect_timeout,
    }

    # SSL / TLS configuration for Amazon RDS MySQL
    db_ssl_mode_raw = get_env("DB_SSL_MODE") or ""
    db_ssl_mode = db_ssl_mode_raw.strip().upper()

    db_ssl_ca_raw = get_env("DB_SSL_CA") or ""
    db_ssl_ca = db_ssl_ca_raw.strip()

    db_ssl_require_raw = get_env("DB_SSL_REQUIRE") or "False"
    db_ssl_require = str(db_ssl_require_raw).strip().lower() in ("true", "1", "yes")

    # Validate explicit SSL mode if provided
    if db_ssl_mode and db_ssl_mode not in VALID_DB_SSL_MODES:
        raise ImproperlyConfigured(
            f"Invalid DB_SSL_MODE '{db_ssl_mode}'. Must be one of: {', '.join(VALID_DB_SSL_MODES)}."
        )

    # Validate CA bundle path if specified
    if db_ssl_ca:
        ca_path = Path(db_ssl_ca)
        if not ca_path.is_file():
            raise ImproperlyConfigured(
                f"Configured DB_SSL_CA file does not exist or is not a valid file: '{db_ssl_ca}'."
            )

        # Disallow weakening certificate verification when CA bundle is explicitly provided
        if db_ssl_mode in ("DISABLED", "PREFERRED", "REQUIRED"):
            raise ImproperlyConfigured(
                f"Cannot use DB_SSL_MODE='{db_ssl_mode}' when DB_SSL_CA is configured. "
                "Certificate verification cannot be disabled or weakened. "
                "Use 'VERIFY_IDENTITY' (recommended) or 'VERIFY_CA'."
            )

        db_options["ssl"] = {"ca": str(ca_path)}
        # Default to strict hostname & certificate verification when CA is provided
        db_options["ssl_mode"] = db_ssl_mode if db_ssl_mode else "VERIFY_IDENTITY"

    elif db_ssl_mode:
        if db_ssl_mode in ("DISABLED", "PREFERRED") and db_ssl_require:
            raise ImproperlyConfigured(
                f"Cannot use DB_SSL_MODE='{db_ssl_mode}' when DB_SSL_REQUIRE is enabled."
            )
        db_options["ssl_mode"] = db_ssl_mode

    elif db_ssl_require:
        db_options["ssl_mode"] = "REQUIRED"

    return {
        "ENGINE": "django.db.backends.mysql",
        "NAME": db_name,
        "USER": db_user,
        "PASSWORD": db_password,
        "HOST": db_host,
        "PORT": str(db_port),
        "CONN_MAX_AGE": db_conn_max_age,
        "CONN_HEALTH_CHECKS": db_conn_health_checks,
        "OPTIONS": db_options,
    }


DATABASES = {
    "default": build_database_config(),
}




# ============================================================
# Password hashing (bcrypt compliant per Capstone Rules)
# ============================================================

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.BCryptPasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]


# ============================================================
# Password validation
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ============================================================
# Internationalization
# ============================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ============================================================
# Static files (CSS, JavaScript, Images)
# ============================================================

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Avoid build/runtime failure if third-party CSS contains missing file references
WHITENOISE_MANIFEST_STRICT = False


# ============================================================
# Media / File uploads (Local Filesystem default / Optional Amazon S3)
# ============================================================

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Optional Amazon S3 Resume Storage
# Enabled only when AWS_STORAGE_BUCKET_NAME is explicitly set in environment.
# Local development defaults to FileSystemStorage (media/ directory).
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME", "").strip()

if AWS_STORAGE_BUCKET_NAME:
    AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "us-east-1").strip()
    AWS_S3_SIGNATURE_VERSION = os.getenv("AWS_S3_SIGNATURE_VERSION", "s3v4").strip()

    s3_options = {
        "bucket_name": AWS_STORAGE_BUCKET_NAME,
        "region_name": AWS_S3_REGION_NAME,
        "signature_version": AWS_S3_SIGNATURE_VERSION,
        # Private bucket policy: do not send public ACLs
        "default_acl": None,
        # Generate pre-signed temporary URLs for private resumes
        "querystring_auth": True,
        "querystring_expire": int(os.getenv("AWS_QUERYSTRING_EXPIRE", "3600")),
        "file_overwrite": False,
    }

    # Optional credentials override; in App Runner/ECS prefer IAM task role
    aws_access_key = os.getenv("AWS_ACCESS_KEY_ID", "").strip()
    aws_secret_key = os.getenv("AWS_SECRET_ACCESS_KEY", "").strip()
    if aws_access_key and aws_secret_key:
        s3_options["access_key"] = aws_access_key
        s3_options["secret_key"] = aws_secret_key

    # Custom endpoint for LocalStack or custom S3-compatible endpoints
    aws_s3_endpoint_url = os.getenv("AWS_S3_ENDPOINT_URL", "").strip()
    if aws_s3_endpoint_url:
        s3_options["endpoint_url"] = aws_s3_endpoint_url

    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": s3_options,
    }



# ============================================================
# Django REST Framework
# ============================================================

from datetime import timedelta

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "EXCEPTION_HANDLER": "hiring.core.exceptions.custom_exception_handler",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
}


# ============================================================
# OpenAPI / Swagger Documentation (drf-spectacular)
# ============================================================

SPECTACULAR_SETTINGS = {
    "TITLE": "Internship & Campus Hiring Platform API",
    "DESCRIPTION": "REST API documentation for campus placement drives, applications, interviews, and offers.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
}


# ============================================================
# CORS Settings (Secure Configuration)
# ============================================================

CORS_ALLOW_ALL_ORIGINS = False

DEFAULT_CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# In production, CORS_ALLOWED_ORIGINS can be supplied as a comma-separated list
# of allowed origins (e.g. https://main.d123.amplifyapp.com).
# If unset or empty, defaults to local Vite/React dev origins.
_raw_cors = os.getenv("CORS_ALLOWED_ORIGINS", "")
if _raw_cors.strip():
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in _raw_cors.split(",") if origin.strip()]
else:
    CORS_ALLOWED_ORIGINS = list(DEFAULT_CORS_ALLOWED_ORIGINS)


CORS_ALLOW_CREDENTIALS = True


# ============================================================
# CSRF Trusted Origins (Required for Django 4+ / 6+ behind HTTPS proxies)
# ============================================================

_raw_csrf = os.getenv("CSRF_TRUSTED_ORIGINS", "")
if _raw_csrf.strip():
    CSRF_TRUSTED_ORIGINS = [orig.strip() for orig in _raw_csrf.split(",") if orig.strip()]
else:
    CSRF_TRUSTED_ORIGINS = []
    for orig in CORS_ALLOWED_ORIGINS:
        if orig.startswith("http://") or orig.startswith("https://"):
            CSRF_TRUSTED_ORIGINS.append(orig)

if _railway_domain:
    _rw_origin = f"https://{_railway_domain}"
    if _rw_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_rw_origin)


# ============================================================
# Logging Configuration
# ============================================================

def build_logging_config(env=None):
    """
    Constructs the logging dictionary configuration with environment-driven log levels.
    Supports DJANGO_LOG_LEVEL and APP_LOG_LEVEL (default: INFO).
    Configures loggers for hiring, django.request, django.security, and django.server.
    """
    if env is None:
        env = os.environ

    valid_levels = {"DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"}

    django_log_level = (env.get("DJANGO_LOG_LEVEL") or "INFO").strip().upper()
    if django_log_level not in valid_levels:
        django_log_level = "INFO"

    app_log_level = (env.get("APP_LOG_LEVEL") or "INFO").strip().upper()
    if app_log_level not in valid_levels:
        app_log_level = "INFO"

    return {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "standard": {
                "format": "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
                "datefmt": "%Y-%m-%d %H:%M:%S",
            },
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "standard",
            },
        },
        "loggers": {
            "hiring": {
                "handlers": ["console"],
                "level": app_log_level,
                "propagate": False,
            },
            "django.request": {
                "handlers": ["console"],
                "level": "WARNING" if django_log_level != "DEBUG" else "DEBUG",
                "propagate": False,
            },
            "django.security": {
                "handlers": ["console"],
                "level": "WARNING" if django_log_level != "DEBUG" else "DEBUG",
                "propagate": False,
            },
            "django.server": {
                "handlers": ["console"],
                "level": django_log_level,
                "propagate": False,
            },
        },
    }


LOGGING = build_logging_config()
