# Generated by Django 6.0.7 on 2026-09-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0004_drive_application_interview_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='allowed_departments',
            field=models.CharField(default='All', help_text="Comma-separated allowed departments (e.g. CSE, IT, ECE) or 'All'", max_length=255),
        ),
        migrations.AddField(
            model_name='drive',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='drive',
            name='min_cgpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('SELECTED', 'Selected'), ('OFFERED', 'Offered'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=30),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='drive',
            name='eligibility',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='interview',
            name='mode',
            field=models.CharField(default='Online', max_length=50),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CLEARED', 'Cleared'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=30),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('student', 'drive'), name='unique_student_drive_application'),
        ),
    ]
